In [2]:
import numpy as np 
import pandas as pd

In [6]:
dict1={
    "name":['harry','aj','pj','dj'],
    "marks":[12,25,4,62],
    "city":['kanpur','rampur','us','uae']
      }

In [7]:
df=pd.DataFrame(dict1)

In [8]:
df

    name  marks    city
0  harry     12  kanpur
1     aj     25  rampur
2     pj      4      us
3     dj     62     uae

In [9]:
df.to_csv("test.csv")

In [10]:
df.to_csv("test2.csv",index=False)

In [11]:
df.head(2)

    name  marks    city
0  harry     12  kanpur
1     aj     25  rampur

In [12]:
df.tail(2)

  name  marks city
2   pj      4   us
3   dj     62  uae

In [14]:
df.describe()

           marks
count   4.000000
mean   25.750000
std    25.669372
min     4.000000
25%    10.000000
50%    18.500000
75%    34.250000
max    62.000000

In [15]:
ex=pd.read_csv("test.csv")

In [16]:
ex

   Unnamed: 0   name  marks    city
0           0  harry     12  kanpur
1           1     aj     25  rampur
2           2     pj      4      us
3           3     dj     62     uae

In [17]:
ex["city"]

0    kanpur
1    rampur
2        us
3       uae
Name: city, dtype: object

In [18]:
ex.index=["one","two","three","four"]

In [19]:
ex

       Unnamed: 0   name  marks    city
one             0  harry     12  kanpur
two             1     aj     25  rampur
three           2     pj      4      us
four            3     dj     62     uae